### ISSUE TITLE
Output API

### ISSUE THREAD

**Issue by suhr** [overdrivenpotato/rust-vst2#18]
The `Plugin` trait seems to lack any output methods like `processReplacing` or `sendVstEventsToHost`.

**Comment by Boscop** [comment]
There are process() and process_f64() for audio output and the Host opCode [ProcessEvents](https://github.com/overdrivenpotato/rust-vst2/blob/master/src/host.rs#L47) which is sendVstEventsToHost.
But currently the Host doesn't relay the incoming midi events, it just ignores them...
But it would be easy to add a handler for that.
[We should add a method like this to the host.](https://github.com/overdrivenpotato/rust-vst2/blob/18fceb9b5ad60cdc28433e376fd1ca5c5b01e702/src/host.rs#L587).
[And then do the dispatching on the host like this.](https://github.com/overdrivenpotato/rust-vst2/blob/bbf8d0cb09f2f23fb7048e6a009400e0b49368f4/src/interfaces.rs#L172)
So that it can be called just like host.automate():

``` rust
host.process_events(events);
```

**Comment by suhr** [comment]
So, `AudioBuffer` is bidirectional? Well, that was not very clear from the documentation.
(I wanted MIDI output though)

**Comment by overdrivenpotato** [comment]
Fixed in #19.

About `AudioBuffer`, the current description is:

> A buffer containing `ChannelBuffer` buffers for each input/output.

Any suggestions on how to make this clearer?

**Comment by augustl** [comment]
I'm a complete noob, so maybe I'm reading this the wrong way.

But isn't OP talking about plugins having the ability to send MIDI events to the outside world? While the first response is about hosts being able to send MIDI events to plugins?

I'm trying to figure out how to write a plugin that sends MIDI events, and I can't seem to figure it out. This issue is the closest I've gotten :)

**Comment by Boscop** [comment]
@augustl There isn't much going on here.. Please join our [telegram group](https://t.me/joinchat/BfEhnw0l4386Uzi5elmGrQ). Sending MIDI events is not very complicated :)
